{{ if .Values.component.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ .Chart.Name }}
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 120
  # HPA reference (optional)
  # autoscalerRef:
  #   apiVersion: autoscaling/v2beta1
  #   kind: HorizontalPodAutoscaler
  #   name: backend
  service:
    # container port
    port: 80
  # promote the canary without analysing it (default false)
  skipAnalysis: false
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # Istio Prometheus checks
    metrics:
      {{ if .Values.component.canary.errorRate.enabled }}
      - name: error-rate
        templateRef:
          name: error-rate
          namespace: istio-system
        thresholdRange:
          max: {{ .Values.component.canary.errorRate.thresholdRange }}
        interval: 30s
      {{ end }}
      {{ if .Values.component.canary.latency.enabled }}
      - name: latency
        templateRef:
          name: latency
          namespace: istio-system
        thresholdRange:
          max: {{ .Values.component.canary.latency.thresholdRange }}
        interval: 30s
      {{ end }}
    # tests (optional)
    # webhooks:
    #   - name: conformance-test
    #     type: pre-rollout
    #     timeout: 15s
    #     url: http://flagger-loadtester.prod/
    #     metadata:
    #       type: bash
    #       cmd: "curl -sd 'test' http://backend-canary.prod:9898/token | grep token"
    #   - name: load-test
    #     type: rollout
    #     timeout: 15s
    #     url: http://flagger-loadtester.prod/
    #     metadata:
    #       type: cmd
    #       cmd: "hey -z 1m -q 10 -c 2 http://backend-canary.prod:9898/"
    #       logCmdOutput: "true"
{{ end }}